# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: e1ec87d8357f617e2b7b234f5389c1c1edb00d6ea933ee0f8aca9caa933bfecbef0293c4f0366951bbf76b739ef7cdd658a7ddc8f6eb66bd0bb06c1c8f052f56

  ldap:
    host: <%= ENV['LDAP_HOST'] %>
    port: <%= ENV['LDAP_PORT'] %>
    users: <%= ENV['LDAP_USERS'] %>
    groups: <%= ENV['LDAP_GROUPS'] %>
    user: <%= ENV['LDAP_USER'] %>
    password: <%= ENV['LDAP_PASS'] %>
    ssl: <%= ENV['LDAP_SSL'] %>


test:
  domain_name: example.com 
  secret_key_base: f875497e1c7700693337ac4f008c8ea33f70929c99ed045f32bfec81519a81075e75e6b6181d2ff503d8603f8d5b42d8ec41e26ff0cfffaa3f356b5946799204

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
